# Generated by Django 4.1.3 on 2022-11-21 23:02

from django.db import migrations, models
import django.db.models.deletion
import pandemic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, null=True)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('BLACK', 'Black'), ('RED', 'Red')], max_length=50)),
                ('has_research_center', models.BooleanField(default=False)),
                ('diseases', models.JSONField(default=pandemic.models.default_city_diseases)),
                ('position', models.JSONField(default=pandemic.models.default_position)),
                ('neighbors', models.ManyToManyField(to='pandemic.city')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('next_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pandemic.player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_in_city', to='pandemic.city')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pandemic.card')),
            ],
            bases=('pandemic.card',),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_outbreak', models.IntegerField(default=0)),
                ('current_spreading_rate', models.IntegerField(default=0)),
                ('are_antidotes_found', models.JSONField(default=pandemic.models.default_antidotes)),
                ('current_player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pandemic.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pandemic.world'),
        ),
        migrations.AddField(
            model_name='city',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='pandemic.world'),
        ),
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pandemic.city'),
        ),
        migrations.CreateModel(
            name='CheatCard',
            fields=[
                ('playercard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pandemic.playercard')),
            ],
            bases=('pandemic.playercard',),
        ),
        migrations.CreateModel(
            name='EpidemicCard',
            fields=[
                ('playercard_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pandemic.playercard')),
            ],
            bases=('pandemic.playercard',),
        ),
        migrations.AddField(
            model_name='playercard',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='pandemic.player'),
        ),
        migrations.AddField(
            model_name='playercard',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_cards', to='pandemic.world'),
        ),
        migrations.CreateModel(
            name='DiseaseCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pandemic.card')),
                ('is_discarded', models.BooleanField(default=False)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_cards', to='pandemic.world')),
            ],
            bases=('pandemic.card',),
        ),
    ]
