# Generated by Django 4.1.3 on 2022-11-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='position',
            new_name='city',
        ),
    ]
