# Generated by Django 4.1.3 on 2022-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0002_rename_position_player_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='world',
            name='current_player',
        ),
        migrations.AddField(
            model_name='city',
            name='is_current_player',
            field=models.BooleanField(default=False),
        ),
    ]
