# Generated by Django 4.1.3 on 2022-11-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandemic', '0003_remove_world_current_player_city_is_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_current_player',
            field=models.BooleanField(default=False),
        ),
    ]
